/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:b71ee820-6da7-4b80-96de-101a3a7cb6ba",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_vHzwSzMFB",
    "aws_user_pools_web_client_id": "7vhigu2b19otbv0jfah667gu0",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://y5ukjh2b45bz5by4mjy5akqjam.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-kmrfojnqmnfkvadauzcfsjibse",
    "aws_user_files_s3_bucket": "notes224448-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
